### ISSUE TITLE
Incorrect Syntax in several pillars

### ISSUE THREAD

**Issue by dh34992** [aws-samples/aws-sap-lens-well-architected#1]
Attempted to create the custom SAP lens by importing the SAP json file (wafsap-v2.0), but the tool rejects the json due to the existence of illegal characters in many of the descriptions.

"?" - question mark
"'" - apostrophe

Example:    At line 808:
"To help protect against malicious activities, follow the guidelines set out within your **organization’s** security framework."

**Comment by dh34992** [comment]
Once I removed the apostrophe's and question marks, the json imported successfully

**Comment by ebilbaoANZ** [comment]
Hi David, thank you for the submission. I just tested this on 3 separate AWS accounts and I don't seem to get this problem - the file imports correctly for me into the AWS Console Well-Architected "Custom Lens" tool. Question marks and apostrophes should be valid characters to import so long as enclosed by double quotation marks as per https://docs.aws.amazon.com/wellarchitected/latest/userguide/lenses-format-specification.html. Are you attempting to import this somewhere else?  Maybe this could be a file format problem on your side? Please reach out to me on LinkedIn and we can connect via email for support if needed.
